### ISSUE TITLE
Using without Arduino

### ISSUE THREAD

**Issue by confile** [adafruit/Adafruit_VS1053_Library#17]
I just bought this product: https://www.adafruit.com/products/1381

Can I use this lib without Arduino?

I want to use ESP8266 with NodeMCU firmware and the VS1053 breakout board.

When I later build my production system with an VS1053 chip can I use this lib as well?

**Comment by ladyada** [comment]
we've tested
https://www.adafruit.com/products/2821
with
https://www.adafruit.com/products/3357
so as long as the wiring is identical it will work
