### ISSUE TITLE
!digitalRead should be digitalRead on line 106 of ogg record

### ISSUE THREAD

**Issue by nicshackle** [adafruit/Adafruit_VS1053_Library#18]
https://github.com/adafruit/Adafruit_VS1053_Library/blob/master/examples/record_ogg/record_ogg.ino#L106

The begin recording, !digitalRead should evaluate to true, but not to end recording.

**Comment by bhass1** [comment]
Suggest closing this issue. Fixed in 44546d4207c2c187e61a04f29a277bbd8a7bfaad

**Comment by caternuson** [comment]
Closing. Should be fixed by #38
