### ISSUE TITLE
Missing FeatherWing examples

### ISSUE THREAD

**Issue by bbx10** [adafruit/Adafruit_VS1053_Library#19]
- Arduino board:  Any Feather

- Arduino IDE version (found in Arduino -> About Arduino menu):  Any version

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 

https://learn.adafruit.com/adafruit-music-maker-featherwing/midi-synth

This tutorial refers to example programs feather_midi and feather_player but these programs are not present in this repo.

**Comment by ladyada** [comment]
eep here ya go! https://github.com/adafruit/Adafruit_VS1053_Library/commit/30d57cf85db90d2411d62c36ce57816d4c9a3cba
