### ISSUE TITLE
_cardCS not set

### ISSUE THREAD

**Issue by mitchellpontague** [adafruit/Adafruit_VS1053_Library#26]
Hey,
In the FilePlayer constructors the pin on `_cardCS` is set high, however i cannot see anywhere `_cardCS` is being set and believe it is supposed to be just the local variable `cs` instead.
On my board the value of `_cardCS` is defaulting to 64 on power on and is causing a crash.
Thanks, Mitchell

**Comment by TheNitek** [comment]
Actually I wounder whether it would make sense to remove the cardCS part completely. Didn't work anyway without any negativ side effects.

**Comment by ladyada** [comment]
fixed and also moved that code (which admittedly isnt used) to begin() since some arduino's dont like to do pin stuff before setup() :)
