### ISSUE TITLE
Can't Import Library

### ISSUE THREAD

**Issue by zombiepigdragon** [adafruit/Adafruit_VS1053_Library#31]
Every time I try to import the .zip, I recieve the following error: "The library "Adafruit_VS1053_Library cannot be used. Library names must contain only basic letters and numbers. (ASCII only and no spaces, and it cannot start with a number)" Why isn't it working?

**Comment by TheNitek** [comment]
Why don't you use the Library Manager from ArduinoIDE to do the download? No zip file necessary

**Comment by zombiepigdragon** [comment]
@TheNitek Okay, I'll be honest. This was stupid. I was using an outdated version, and forgot to update. Thanks for pointing out the easy way!
