### ISSUE TITLE
musicPlayer.useInterrupt broken since 1.0.3

### ISSUE THREAD

**Issue by fwachsmuth** [adafruit/Adafruit_VS1053_Library#36]
Using a Pro Micro or Lenoardo (32U4) and Arduino 1.8.3, the player_interrupts.ino example fails to finish track playback using the Interrupt method. After a certain amount of time, DREQ just goes HIGH and stays high, playback stops. 
With 1.0.2 or earlier, this does not happen.

**Comment by caternuson** [comment]
Tested this with a Feather 32u4 and could not recreate the issue using the 1.2.1 release of the library.

Please retest with current library release and see if issue still exists.

**Comment by caternuson** [comment]
Closing. Can reopen if still an issue.
