### ISSUE TITLE
player eventually freezes

### ISSUE THREAD

**Issue by hoosierEE** [adafruit/Adafruit_VS1053_Library#4]
The feedBuffer() method relies on DREQ for determining when it is okay to grab more bytes from the SD card, but according to the [datasheet](http://www.vlsi.fi/fileadmin/datasheets/vlsi/vs1053.pdf) this is not sufficient, as DREQ can change for other reasons besides "ready for data". 

In my sketch I noticed that repeatedly calling startPlayingFile() will eventually cause the Arduino to freeze, and when it does the DREQ pin remains low.

Doing a softReset() of the VS1053 prevents the freezing, but that is not ideal.

**Comment by ladyada** [comment]
not sure but we've just pulled some lock-tweaks - please reopen if it still happens!

**Comment by hoosierEE** [comment]
Hey, I hate it when OP abandons the thread, but unfortunately I won't be able to confirm the fix in the foreseeable future as I'm busy with other projects.  Thanks for working on it though, hopefully the next person to use this will benefit.

**Comment by jonfroehlich** [comment]
Just a note that I ran into this problem today using the Adafruit VS1053 Library (v1.2.1) with the Adafruit Feather nRF52840 board and [Adafruit MP3 Featherwing](https://www.adafruit.com/product/3357).

I built a simple MP3 player that reads all .mp3 filenames from the SD card and plays MP3s with the `musicPlayer.startPlayingFile` function. You can navigate next/previous using either Serial commands or buttons. For example, pressing `n` in Serial Console would start playing the next song.

Needless to say, `startPlayingFile` was intermittently but consistently crashing—sometimes after playing parts of 3 songs, sometimes 10 or 15 but eventually it would happen if you hit "next" enough.

I tried a range of things but eventually landed on calling `noInterrupts()` before `musicPlayer.stopPlaying()` and then not re-enabling interrupts myself but instead relying on the fact that the `musicPlayer.startPlayingFile` function calls `interrupts()` itself (and thus re-enables interrupts there).

If you want to see the source code, check it out here: https://github.com/makeabilitylab/arduino/blob/master/PlayingMusic/SimpleMp3Player/SimpleMp3Player.ino

Hope it helps someone.
