### ISSUE TITLE
SPI Max Speed Issues on M0

### ISSUE THREAD

**Issue by GabrielGoldsteinAnidea** [adafruit/Adafruit_VS1053_Library#46]
Value of 8Mhz not supported (no sound) on M0 chip.  Reduced to 4Mhz for reliable audio.

Line 41 of Adafruit_VS1053.cpp: 
#define VS1053_DATA_SPI_SETTING     SPISettings(4000000, MSBFIRST, SPI_MODE0)

- Arduino board:  Feather M0/Generic M0

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.6/1.9

**Comment by caternuson** [comment]
This may have been resolved by BSP or other updates. Tested feather_player on a Feather M0 Basic Proto and it ran as expected.

Closing. Can reopen if still an issue.
