### ISSUE TITLE
Cant compile record_ogg

### ISSUE THREAD

**Issue by SeZAKxing** [adafruit/Adafruit_VS1053_Library#47]
record_ogg:173: error: '_BV' was not declared in this scope
     if (! (musicPlayer.sciRead(VS1053_SCI_AICTRL3) & _BV(2))) {
- Arduino board:  m0 WiFi Feather(3061) w/ Music Maker FeatherWing (3357)

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.3

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): 
File->examples->Adafruit VS1053 Library-> record_ogg
Verify/Compile (ctrl-R)

**Comment by ladyada** [comment]
try replacing _BV(2) with (1<<2)

**Comment by caternuson** [comment]
Closing. Probably fixed now:
https://github.com/adafruit/Adafruit_VS1053_Library/blob/aedb7bbce6e83acb5e48ce7a93e10d3a5afe3bf0/Adafruit_VS1053.cpp#L34-L36
