### ISSUE TITLE
Distorted *.wav files

### ISSUE THREAD

**Issue by MahmubulH** [adafruit/Adafruit_VS1053_Library#48]
Arduino Board: MEGA2560
IDE Version: 1.8.5

I've connected the VS1053 and started playing audio.
MP3 files work great, but WAV files produce distortion.

The shield datasheet says it is able to support wav files so I am lead to believe the problem is from this library?

**Comment by ladyada** [comment]
your chip isnt fast enough to play WAVs, they're large and require a lot of data passing. use a faster chip, or MP3
