### ISSUE TITLE
setVolume ranges?

### ISSUE THREAD

**Issue by johnwargo** [adafruit/Adafruit_VS1053_Library#60]
For this library's `void Adafruit_VS1053::setVolume(uint8_t left, uint8_t right) {` method - what are the possible range of values?  In the sample app you have:

```c
 // Set volume for left, right channels. lower numbers == louder volume!
  musicPlayer.setVolume(10, 10);
```
but no mention of whether this is a small value (10) or big value. 

I'm assuming 0-255, but I can't tell from looking at the sample or any comments in the source.

**Comment by ladyada** [comment]
yes its 0-255
